In [ ]:
#1.Write a Python Program to Add Two Matrices?
import numpy as np  # numpy module
def add_mat(A,B):
  A=np.array(A)
  B=np.array(B)
  return np.add(A,B)  
add_mat([[1,2],[3,4]],[[1,2],[3,4]])      

array([[2, 4],
       [6, 8]])

In [ ]:
#2.Write a Python Program to Multiply Two Matrices?
import numpy as np
def mult_mat(A,B):
  A=np.array(A)
  B=np.array(B)
  return np.dot(A,B) 
mult_mat([[1,2],[3,4]],[[1,2],[3,4]])        


array([[ 7, 10],
       [15, 22]])

In [ ]:
#3.Write a Python Program to Transpose a Matrix?
import numpy as np
def tranp_mat(A):
  matrix=np.array(A)
  return matrix.transpose()
tranp_mat([[1,2],[3,4]])

array([[1, 3],
       [2, 4]])

In [ ]:
#4.Write a Python Program to Sort Words in Alphabetic Order?
def sort_aplha():
  str1=input()
  words=[word.lower() for word in str1.split()]
  words.sort()
  print("The sorted words are:")
  for word in words:
    print(word)
sort_aplha()    


This is my first ineuron python class
The sorted words are:
class
first
ineuron
is
my
python
this


In [ ]:
from numpy.testing._private.utils import clear_and_catch_warnings
#5.Write a Python Program to Remove Punctuation From a String?
def rem_punc():
  punctuation= '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
  str2=input("Enter the string :")
  for char in str2.lower():
    if char in punctuation:
      str2=str2.replace(char," ")
  return "The new string ",str2    
rem_punc()      

Enter the string :@##$%^&&1561718manihajjakas!&&!(!


('The new string ', '        1561718manihajjakas      ')